### ISSUE TITLE
聊天的 clientId 里面不能含有 @ 字符

### ISSUE THREAD

**Issue by jwfing** [leancloud/LeanCloudChatKit-Android#11]
com.avos.avoscloud.im.v2.AVIMException: com.avos.avoscloud.AVException: android.database.sqlite.SQLiteException: near "@lean": syntax error (code 1): , while compiling: CREATE TABLE IF NOT EXISTS profilecache_mj@lean.com(id TEXT PRIMARY KEY NOT NULL, content TEXT )
抛这个异常，我们本地建缓存数据库的时候出错了

**Comment by daweibayu** [comment]
#14
