### ISSUE TITLE
LCChatProfileProvider 提供的 UserProfile 如果 avatar 为 空，会 crash

### ISSUE THREAD

**Issue by jwfing** [leancloud/LeanCloudChatKit-Android#12]
java.lang.IllegalArgumentException: Path must not be empty.
                                                                            at com.squareup.picasso.Picasso.load(Picasso.java:297)
                                                                            at cn.leancloud.chatkit.viewholder.LCIMChatItemHolder$1.internalDone0

**Comment by daweibayu** [comment]
#14
