### ISSUE TITLE
不能拍照发图，只能选图库的发，拍照会提示 login first

### ISSUE THREAD

**Issue by invinjun** [leancloud/LeanCloudChatKit-Android#16]
另外android和ios的UI完全对不上，low啊，同志们leancloud的设计师都被ios程序员潜规则了么？ 还有ios的表情安卓只能显示文字 。。iso发的图片安卓显示的是旋转过了，方向不对。相信你们也都了解这些问题。。什么时候有稳定完善的版本呢

**Comment by daweibayu** [comment]
1. UI 的统一我们稍后会完成，这个我们正在做。
2. 表情包稍后我们讨论下该怎么处理。
3. 关于拍照发图，我这边的实测是没有问题，如果抛出 login first，应该是没有调用 LCChatKit.open 就直接使用 LCIMConversationActivity 造成的，具体流程的话可以参考 https://leancloud.cn/docs/chatkit-android.html 或者看 chatkitapplication demo 代码。
4. 关于图片，Android 这边并没有做旋转处理。

**Comment by invinjun** [comment]
谢谢您的及时回复！
关于拍照发图是偶发现象，并且确实登陆过了，直接选图可以只是拍照提示，现在测试没有问题了，
另外 经过测试IOS直接发手机里面的下载的图片没问题，但是IOS拍照或者拍照保存在相册里的图片发送过来就是旋转的，ios自己显示的是正确的，只有安卓的旋转了

**Comment by invinjun** [comment]
@daweibayu 另外对话界面每次直接打开的时候并没有最近对话列表，只有发起一次对话才有对话列表。
恩 方便加个微信么 (invinjun）？可以方便反映一些情况。 去年有个leancloud的支持群，换手机找不到了....
