### ISSUE TITLE
Chatkit的android版本是否有"聊天列表"?

### ISSUE THREAD

**Issue by EggsyChiang** [leancloud/LeanCloudChatKit-Android#17]
你好，我是你們的客戶，因為看demo的截圖只有"連絡人"列表，想請問Chatkit的android版本是否有"聊天列表"?可以截圖給我們看嗎?因為Android版本的demo似乎不像ios版本那麼清楚。另外"聊天列表"在哪裡如何叫出呢?謝謝

![2016-08-10 12 10 24](https://cloud.githubusercontent.com/assets/19549193/17550008/90b09684-5f25-11e6-9ef1-f1c762a0651d.png)

**Comment by daweibayu** [comment]
你好，是有聊天列表的，这个页面有两个 tab，一个 tab 是联系人页面，另一个 tab 会话就是聊天列表，就是你标出来的那个 tab 页面。
具体的 UI 可以运行 ChatKit 里边的 demo 查看。
