### ISSUE TITLE
chakit通知栏消息点击后 跳转对话界面错误

### ISSUE THREAD

**Issue by invinjun** [leancloud/LeanCloudChatKit-Android#21]
之前在清单文件加了 <action android:name="cn.leancloud.chatkit.chat_notification_action"/>之后 跳转是没问题的，最近这几天测试突然就不对了 多个对话的时候总是跳转第一个对话 ，以为是我修改了某些代码，然后下载了最新的源码加入这个action之后测试 发现同样问题，是不是有做过什么修改呢

**Comment by daweibayu** [comment]
前几天确实发布了一个新版本，但是应该不涉及到你说的地方。关于点击总是跳转第一个对话的问题，建议 debug 找一下问题原因。在发送 Intent 的地方打个断点，然后看一下到底是发送的数据有问题，还是接收的处理问题。

**Comment by invinjun** [comment]
发送和接收都没问题，可能是pendingintent的问题，每次内容只显示最近的一条推送，多个聊天只显示最近一条聊天推送，chakit中最后一个flag的参数是0，会导致第二条推送到达后内容更新了，但是点击还是第一次收到的intent的跳转，修改为FLAG_UPDATE_CURRENT后可以正常跳转，现在就是推送消息只有一条，不知道如何改为多个通知

**Comment by invinjun** [comment]
搞定了，notify的第一个参数修改了 就可以了
