### ISSUE TITLE
和leancloud的4.4.4版本的基础包不兼容, 找不到okhttp

### ISSUE THREAD

**Issue by anoreg** [leancloud/LeanCloudChatKit-Android#58]
Error:(7, 33) error: package com.avos.avoscloud.okhttp does not exist
Error:(8, 33) error: package com.avos.avoscloud.okhttp does not exist
Error:(9, 33) error: package com.avos.avoscloud.okhttp does not exist
Error:(10, 33) error: package com.avos.avoscloud.okhttp does not exist
Error:(44, 18) error: cannot find symbol class OkHttpClient
Error:(49, 24) error: cannot find symbol class OkHttpClient
Error:(131, 5) error: cannot find symbol class Call
Error:(131, 49) error: package Request does not exist
Error:(135, 7) error: cannot find symbol class Response

**Comment by jwfing** [comment]
请使用我们最新版 sdk，我们已经切换到官方的 okhttp 库了。
