### ISSUE TITLE
v4.5.4 在 app 被后台杀掉后没有自动 open

### ISSUE THREAD

**Issue by BinaryHB** [leancloud/LeanCloudChatKit-Android#67]
从日志可以看到，在应用被杀后，有 cmd: login 和 cmd: loggedin 的日志，但是没有 cmd: open 的日志。

![wechatimg171](https://user-images.githubusercontent.com/6046086/32883853-248e0c00-ca7e-11e7-9b99-88de74f71ae0.jpeg)

**Comment by jwfing** [comment]
新版 sdk （v4.5.5）解决这个问题

**Comment by jwfing** [comment]
用户需求理解有误，先关闭这个 issue。
