### ISSUE TITLE
一对一聊天修改默认头像？

### ISSUE THREAD

**Issue by WaylanPunch** [leancloud/LeanCloudChatKit-Android#9]
LCIMConversationFragment.java 如何修改默认的头像，如下图
![img](https://dn-lhzo7z96.qbox.me/1461816927540)

https://dn-lhzo7z96.qbox.me/1461816927540
https://leancloud.cn/docs/chatkit-android.html#聊天界面

**Comment by daweibayu** [comment]
上图的头像是具体 User 的图像，如果修改的话可参考 https://github.com/leancloud/LeanCloudChatKit-Android/blob/master/chatkitapplication/src/main/java/cn/leancloud/chatkitapplication/CustomUserProvider.java ，所有的头像 ChatKit 都是通过 LCChatProfileProvider 来与外部交互的。
